name: grapple-legal-chatbot
region: nyc

services:
  - name: server
    github:
      repo: strdr4605/grapple-user-bot
      branch: master
      deploy_on_push: true
    source_dir: /server
    dockerfile_path: Dockerfile
    http_port: 3002
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: PORT
        value: "3002"
      - key: OPENAI_API_KEY
        type: SECRET
        scope: RUN_TIME
      - key: PIPEDRIVE_KEY
        type: SECRET
        scope: RUN_TIME

  - name: client
    github:
      repo: strdr4605/grapple-user-bot
      branch: master
      deploy_on_push: true
    source_dir: /client
    dockerfile_path: Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: ${server.PUBLIC_URL}/api/v1/
        scope: BUILD_TIME
