name: grapple-server
region: nyc

services:
  - name: api
    github:
      repo: strdr4605/grapple-user-bot
      branch: master
      deploy_on_push: true
    source_dir: server
    dockerfile_path: server/Dockerfile
    http_port: 3002
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: PORT
        value: "3002"
      - key: OPENAI_API_KEY
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: PIPEDRIVE_KEY
        type: SECRET
        scope: RUN_AND_BUILD_TIME
