name: grapple-server
region: nyc

services:
  - name: api
    github:
      repo: strdr4605/grapple-user-bot
      branch: master
      deploy_on_push: true
    source_dir: server
    http_port: 3002
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: PORT
        value: "3002"
